/* CLÉ ÉTRANGÈRES ET CONTRAINTES D'INTÉGRITÉ */
ALTER TABLE Products ALTER COLUMN ProductName NVARCHAR(450);
ALTER TABLE Products ALTER COLUMN ProductType NVARCHAR(450);
ALTER TABLE Customers ALTER COLUMN CustomerName NVARCHAR(450);
ALTER TABLE Customers ALTER COLUMN Email NVARCHAR(450);
ALTER TABLE Customers ALTER COLUMN Phone NVARCHAR(450);
ALTER TABLE ProductTypes ALTER COLUMN ProductTypeName NVARCHAR(450);